version: 2

# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -s
      - -w
      - "-X github.com/s-matsubara/test-cli/cmd/version.Version={{ .Version }}"
      - "-X github.com/s-matsubara/test-cli/cmd/version.Commit={{ .ShortCommit }}"
      - "-X github.com/s-matsubara/test-cli/cmd/version.BuildDate={{ .Date }}"

homebrew_casks:
  - name: test-cli
    repository:
      owner: s-matsubara
      name: homebrew-tap
      branch: main
      token: "{{ .Env.GITHUB_TOKEN }}"
